### ISSUE TITLE
code section formatting in readme.md

### ISSUE THREAD

**Issue by Ivan-CBRE** [itArnaudov/public#2]
py -> readme.md has slight formatting issue. please fix when you can @itArnaudov

**Comment by itArnaudov** [comment]
created branch for development fix

**Comment by Ivan-CBRE** [comment]
> created branch for development fix

i'm helping you with a pull request [5dce350](https://github.com/itArnaudov/public/pull/3/commits/5dce3506d6a71179d28c738a067b645151752fde)
